#!/usr/bin/env bash
# Regenerates generated/product-vision-to-user-stories/ from the BPMN, the confirmed design
# decisions (build-spec.mjs), the step content (content/*.json) and the hand-written parts.
# Run from anywhere; everything resolves against examples/dark-factory/ (the example root).
# The output is a snapshot: the plugin built from it now lives, hand-maintained, in the
# ai-sdlc-dojo-2026-factory repo (plugins/dark-factory/); nothing here builds or ships it.
#
# Hand-written files that this script does NOT regenerate (edit them in place under generated/):
#   skills/product-{recherche,kritiker-pruefung,panel-befragung,phasen-gate,traceability,init}/SKILL.md,
#   all scripts/*.mjs + scripts/lib/trace.mjs, hooks/*, knowledge/*.md, README.md
#   (scripts/lib/df.mjs and product-traceability/scripts/lib/contracts.mjs ARE regenerated by gen-files.mjs)
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FACTORY="$(cd "$HERE/../.." && pwd)"   # examples/dark-factory/: BPMN, generated/, tools/
REPO="$(cd "$FACTORY/../.." && pwd)"   # flowforge repo root: .agents/skills/
CACHE="${BPMN_TOOLS_CACHE:-$HOME/.cache/bpmn-authoring-tools}"
BPMN=product-vision-to-user-stories.bpmn
WF=generated/product-vision-to-user-stories
cd "$FACTORY"
mkdir -p "$HERE/.build"

echo "── 1/7 validate BPMN"
bash "$REPO"/.agents/skills/bpmn-authoring/scripts/validate.sh "$BPMN"
echo "── 2/7 inventory + sdlc extraction"
node "$REPO"/.agents/skills/flowforge-analyze/scripts/inventory.mjs "$CACHE" "$BPMN" > "$HERE/.build/inv.json"
python3 "$HERE/extract-sdlc.py" "$BPMN" > "$HERE/.build/sdlc.json"
echo "── 3/7 workflow-spec.yaml"
node "$HERE/build-spec.mjs"
echo "── 4/7 step skills, rubrics, agents"
node "$HERE/gen-files.mjs"
echo "── 5/7 workflow script"
node "$HERE/assemble-workflow.mjs"
echo "── 6/7 mapping report + render"
node "$HERE/gen-report.mjs"
node "$REPO"/.agents/skills/flowforge-generate/scripts/render-mapping.mjs "$CACHE" "$WF/workflow-spec.yaml" "$BPMN" "$WF/mapping"
echo "── 7/7 verify + reference audit + smoke test"
node "$REPO"/.agents/skills/flowforge-verify/scripts/verify.mjs "$CACHE" "$WF"
node "$HERE/check-refs.mjs"
node "$HERE/smoke.mjs" > /dev/null && echo "smoke test ok"
node "$HERE/smoke-stories.mjs" > /dev/null && echo "story smoke ok"
env -u GEMINI_API_KEY node "$HERE/smoke-research.mjs" > /dev/null && echo "research smoke ok"
node "$REPO"/.agents/skills/flowforge-generate/scripts/check-mapping-view.mjs "$CACHE" "$WF/mapping/index.html"
