// Rubric seeds: Gedächtnis §13 core criteria (binding) + adopted notebook criteria.
// [id, text, weight, kill?, source]
const G13 = 'Gedächtnis §13';
export const RUBRICS = {
  'idea-brief': { for: ['S0'], criteria: [
    ['required', 'All required fields (idee, markt/region, ausgabesprache, budget/timebox, zielarchitektur/plattform) are filled', 2, true, G13 + ' / §14'],
    ['inferred-marked', 'Every derived field is marked 🧠 with a one-line justification', 1, false, G13],
    ['budget-architecture', 'Budget/timebox and target architecture are present and plausible', 1, false, G13],
    ['asm-handoff', 'Every 🧠 field is listed for conversion into an ASM item in 1.1.6', 1, false, '§14'],
  ] },
  'research-markt-wettbewerb': { for: ['Call_R1'], criteria: [
    ['market-size', 'Market size/growth as a range with method (top-down/bottom-up) and reference year, triangulated', 2, false, '§8.2'],
    ['competitors', '≥3 direct and ≥2 indirect competitors with positioning, target group, pricing model and price points', 2, false, '§8.2'],
    ['feature-matrix', 'Feature matrix of the direct competitors (≥5 features)', 1, false, '§8.2'],
    ['pricing-benchmarks', 'Price/revenue model benchmarks', 1, false, '§8.2'],
    ['trends', 'Dated market trends of the last 2–3 years', 1, false, '§8.2'],
    ['entry-barriers', 'Market entry barriers', 1, false, '§8.2'],
    ['ledger-only', 'Every statement comes from the claim ledger research/claims/<callId>.json and cites CLM + SRC ids (check-claims.mjs --verify-report is ok)', 2, false, '§8.4'],
    ['triangulation', 'Every key claim is triangulated (≥2 independent sites, ≥1 raw text) or visibly marked 🧠 with untriangulated-key-claim', 2, false, '§8.4'],
    ['tiers-freshness', 'No market/number/competitor claim rests on T3 sources alone; regulation cites a T1 source; market data ≤ 3 years old or flagged', 1, false, '§8.3'],
    ['gaps-explicit', 'Every uncovered scope point is named explicitly as not covered', 1, false, '§8.5'],
  ] },
  'research-zielgruppe-voc': { for: ['Call_R2'], criteria: [
    ['segments', '≥2 target segments with distinguishing traits and rough size', 2, false, '§8.2'],
    ['voc', '≥3 verbatim VoC quotes per segment from ≥2 source types (forums, reviews, social)', 2, false, '§8.2'],
    ['jobs-pains', 'Jobs/pains from user statements (not demographics only), each pain with a quote', 1, false, '§8.2'],
    ['workarounds', 'Current workarounds and switching barriers', 1, false, '§8.2'],
    ['wtp', 'Willingness-to-pay signals', 1, false, '§8.2'],
    ['ledger-only', 'Every statement comes from the claim ledger research/claims/<callId>.json and cites CLM + SRC ids (check-claims.mjs --verify-report is ok)', 2, false, '§8.4'],
    ['triangulation', 'Every key claim is triangulated (≥2 independent sites, ≥1 raw text) or visibly marked 🧠 with untriangulated-key-claim', 2, false, '§8.4'],
    ['tiers-freshness', 'No market/number/competitor claim rests on T3 sources alone; regulation cites a T1 source; market data ≤ 3 years old or flagged', 1, false, '§8.3'],
    ['gaps-explicit', 'Every uncovered scope point is named explicitly as not covered', 1, false, '§8.5'],
  ] },
  'research-domaene-prozesse-regulatorik': { for: ['Call_R3'], criteria: [
    ['as-is', 'As-is domain process in steps with the parties involved', 1, false, '§8.2'],
    ['regulation', 'Applicable regulation/standards with exact reference (law/norm and section, T1 source) or explicitly "none specific"', 2, false, '§8.2'],
    ['case', '≥1 documented practice case and ≥1 negative case from the domain', 1, false, '§8.2'],
    ['terms', 'Domain terms collected as a glossary seed', 1, false, '§8.2'],
    ['ledger-only', 'Every statement comes from the claim ledger research/claims/<callId>.json and cites CLM + SRC ids (check-claims.mjs --verify-report is ok)', 2, false, '§8.4'],
    ['triangulation', 'Every key claim is triangulated (≥2 independent sites, ≥1 raw text) or visibly marked 🧠 with untriangulated-key-claim', 2, false, '§8.4'],
    ['tiers-freshness', 'No market/number/competitor claim rests on T3 sources alone; regulation cites a T1 source; market data ≤ 3 years old or flagged', 1, false, '§8.3'],
    ['gaps-explicit', 'Every uncovered scope point is named explicitly as not covered', 1, false, '§8.5'],
  ] },
  'research-synthese': { for: ['K_3'], criteria: [
    ['verdict-per-claim', 'Every checked claim has a result (confirmed / refuted / unclear)', 2, false, G13],
    ['sources', 'Every result cites ≥1 SRC in an allowed tier; refuted claims name the counter-source', 2, false, '§8.3'],
  ] },
  'vision-statement': { for: ['S1.1.2'], criteria: [
    ['moore', 'Follows the Moore template (For … who … the … is a … that … Unlike … our product …)', 2, false, G13 + ' (Moore, Olsen)'],
    ['no-buzzwords', 'No buzzwords', 1, false, G13],
    ['concrete-customer', 'Target customer is concrete', 1, false, G13],
    ['one-page', 'Fits one page, names problem and differentiator; high-concept pitch present', 1, false, 'Design Thinking Toolbox'],
  ] },
  'lean-canvas': { for: ['S1.1.3'], criteria: [
    ['complete', 'All building blocks filled', 1, false, G13],
    ['evidence-per-cell', 'Every cell carries an evidence level', 1, false, G13],
    ['pricing', 'Pricing model explicit', 2, false, G13],
    ['alternatives', 'Problem box names existing alternatives/workarounds; ≤4 entries per box', 1, false, 'Running Lean'],
  ] },
  'vpc': { for: ['S1.1.5'], criteria: [
    ['linked', 'Jobs/Pains/Gains ↔ Products/Pain Relievers/Gain Creators fully linked', 2, false, G13],
    ['panel-fit', 'Fit rating of the panel present (🤖 marked)', 1, false, G13],
    ['dimensions', 'Jobs cover functional, social and emotional dimensions', 1, false, 'Design Thinking Playbook'],
  ] },
  'assumptions-map': { for: ['S1.1.6'], criteria: [
    ['dfv', 'Every assumption rated for Desirability/Feasibility/Viability', 1, false, G13],
    ['importance-evidence', 'Every assumption placed on Importance × Evidence', 1, false, G13],
    ['kill-marked', 'Kill assumptions (high importance, low evidence) marked', 2, false, G13],
    ['brief-asm', 'All 🧠 fields of the idea brief present as ASM items', 1, false, '§14'],
  ] },
  'impact-map': { for: ['S1.2.1', 'S1.2.2', 'S1.2.3', 'S1.2.4'], criteria: [
    ['hierarchy', 'Strict hierarchy Goal → Actor → Impact → Deliverable', 2, false, G13 + ' (Adzic)'],
    ['measurable-impacts', 'Impacts are measurable behaviour changes', 1, false, G13],
    ['options', 'Deliverables are options, not commitments', 1, false, G13],
    ['omtm', 'Goal defines exactly one OMTM placed on the AARRR funnel', 1, false, 'Lean Analytics (adopted 2026-09-25)'],
  ] },
  'scoring': { for: ['S1.2.5', 'S2.2.5', 'S4.2.4'], criteria: [
    ['disclosed', 'Formula and input values disclosed', 2, false, G13],
    ['recomputable', 'Recomputable: the critic reproduces the ranking from the inputs', 2, false, G13],
    ['consistent', 'Ranking consistent with the values', 1, false, G13],
  ] },
  'roadmap': { for: ['S1.2.6'], criteria: [
    ['outcomes', 'Outcome instead of feature phrasing', 1, false, G13],
    ['links', 'Every milestone references GOAL/IMP items', 1, false, G13],
  ] },
  'panel-grounding': { for: ['S1.1.4', 'S2.1.3'], criteria: [
    ['src-per-trait', 'Every profile trait has an SRC reference', 2, true, G13 + ' / §7.2'],
    ['source-types', '≥3 different source types in the panel; no persona rests on a single source', 1, false, G13],
    ['contrarian-refuser', 'Contrarian and Verweigerer present (full panel only)', 1, false, G13],
    ['hidden', 'Hidden attributes set (budget, skepticism, workaround, switching barriers, secret)', 1, false, '§7.3'],
  ] },
  'interview-guide': { for: ['S2.1.2'], criteria: [
    ['past-behaviour', 'Questions about past behaviour only', 2, false, G13],
    ['no-leading', 'No leading questions', 1, false, G13],
    ['solution-late', 'Solution shown only in the last third', 1, false, G13],
    ['kill-coverage', 'Covers the kill assumptions', 1, false, G13],
    ['problem-ranking', 'Contains the problem-ranking block (top-3 problems, shuffled per persona)', 1, false, 'Testing Business Ideas / Lean Analytics (adopted 2026-09-25)'],
  ] },
  'transcript': { for: ['S2.1.4'], criteria: [
    ['complete', 'Complete for every persona of the panel set', 1, false, G13],
    ['in-role', 'Persona stayed in role', 1, false, G13],
    ['dont-know', '"Weiß nicht" / "ist mir egal" not reinterpreted', 1, false, G13],
    ['ranking-synthesis', 'Problem-ranking result per persona recorded; kill signal stated if core problem not in top 3', 1, false, 'adopted 2026-09-25'],
  ] },
  'persona': { for: ['S2.1.5'], criteria: [
    ['role-title', 'Concrete role title (no generic "user")', 1, false, G13],
    ['jtbd', '1–3 JTBD', 1, false, G13],
    ['pains-gains', 'Top-2 pains and top-2 gains', 1, false, G13],
    ['trigger', 'Trigger situation', 1, false, G13],
    ['evidence', 'Evidence from T/SRC', 2, false, G13],
  ] },
  'jtbd': { for: ['S2.1.6'], criteria: [
    ['syntax', 'Syntax "When …, I want to …, so I can …"', 1, false, G13],
    ['neutral', 'Implementation-neutral (no UI/tech)', 2, false, G13],
  ] },
  'pov-hmw': { for: ['S2.2.1', 'S2.2.2', 'S2.2.3'], criteria: [
    ['neutral', 'Solution-neutral', 2, false, G13],
    ['focused', 'Focused on one persona / one need', 1, false, G13],
    ['verb-need', 'Needs expressed as verbs, not nouns', 1, false, 'Design Thinking Toolbox'],
  ] },
  'ost': { for: ['S2.2.4'], criteria: [
    ['levels', 'Outcome → Opportunities → Solutions → Experiments', 2, false, G13 + ' (Torres)'],
    ['user-view', 'Opportunities phrased from the user perspective', 1, false, G13],
    ['multiple-solutions', 'Several competing solutions per opportunity; no solution directly under the outcome', 1, false, "The Product Manager's Playbook"],
  ] },
  'journey': { for: ['S3.1.1', 'S3.1.2', 'S3.1.3'], criteria: [
    ['structure', 'Phases, touchpoints, emotion curve', 1, false, G13],
    ['hot-spots', 'Every hot spot addressed or skipped with a reason', 2, false, G13],
    ['outside-in', 'Outside-in and end to end (before/during/after)', 1, false, 'Journey Mapping Playbook'],
  ] },
  'service-blueprint': { for: ['S3.1.4'], criteria: [
    ['layers', 'Frontstage / line of visibility / backstage / support systems', 2, false, G13],
    ['complexity', 'Backstage complexity rated', 1, false, G13],
    ['traced', 'Every frontstage interaction traces to a backstage process or system', 1, false, 'Mapping Experiences'],
  ] },
  'story-map': { for: ['S4.1.1', 'S4.1.2', 'S4.1.3', 'S4.1.4', 'S4.1.5', 'S4.2.5'], criteria: [
    ['2d', '2D structure (narrative horizontal, priority vertical)', 1, false, G13 + ' (Patton)'],
    ['no-orphans', 'No orphaned cards', 1, false, G13],
    ['release-line', 'Release line explicit', 1, false, G13],
    ['neutral-backbone', 'Backbone is solution-independent', 1, false, 'Fifty Quick Ideas'],
  ] },
  'walking-skeleton': { for: ['S4.2.2', 'S4.2.3'], criteria: [
    ['steel-thread', 'Steel thread through all layers', 1, false, G13],
    ['minimal', 'Minimal', 1, false, G13],
    ['usable', 'End-to-end usable', 1, false, G13],
  ] },
  'mvp': { for: ['S4.2.1', 'S4.2.5'], criteria: [
    ['fits-budget', 'Fits budget/timebox from the brief', 2, true, G13],
    ['learning-goal', 'Every slice has a learning goal', 1, false, G13],
    ['goal-link', 'References GOAL items', 1, false, G13],
    ['vertical', 'Vertical, balanced slice — not one technical layer', 1, false, 'Lean Enterprise'],
  ] },
  'invest': { for: ['S5.1.1', 'S5.1.3'], criteria: [
    ['connextra', 'Connextra format with a concrete role', 1, false, G13],
    ['independent', 'Independent', 1, false, G13 + ' (Wake, Cohn)'],
    ['negotiable', 'Negotiable', 1, false, G13],
    ['valuable', 'Valuable: "damit" is a user/business outcome', 2, false, G13],
    ['estimable', 'Estimable', 1, false, G13],
    ['small', 'Small (≤ M)', 1, false, G13],
    ['testable', 'Testable', 1, false, G13],
  ], routing: 'Also classify the story: fits | too-big (-> splitting) | too-uncertain (-> spike).' },
  'spike': { for: ['S5.1.4'], criteria: [
    ['timebox', 'Timebox', 1, false, G13],
    ['question', 'Explicit question', 1, false, G13],
    ['ac', 'Acceptance criteria of the spike', 1, false, G13],
  ] },
  'dor': { for: ['S5.2.1', 'S5.2.2', 'S5.2.3', 'S5.2.4'], criteria: [
    ['invest', 'INVEST fulfilled', 2, false, G13 + ' (Scrum, IREB)'],
    ['ac', '≥1 AC (confirmation notes at this stage)', 1, false, G13],
    ['no-blockers', 'No open blockers', 1, false, G13],
    ['glossary', 'Terminology per glossary', 1, false, G13],
    ['size', 'Size class S or M with reasoning (L forces re-splitting)', 1, true, '§4'],
  ] },
  'gherkin': { for: ['S6.1.1', 'S6.1.2', 'S6.1.3', 'S6.1.4'], criteria: [
    ['valid', 'Valid Given-When-Then', 1, false, G13],
    ['paths', '≥1 happy path and ≥1 negative/exception path', 2, false, G13],
    ['neutral', 'Implementation-neutral', 1, false, G13],
    ['sbe', 'SBE examples with concrete values', 1, false, G13 + ' (Adzic)'],
  ] },
  'ubiquitous-language': { for: ['S6.2.3'], criteria: [
    ['one-term', 'One term per concept', 1, false, G13 + ' (Evans)'],
    ['no-contradictions', 'No contradicting domain rules', 1, false, G13],
    ['all-in-glossary', 'All terms in the glossary', 1, false, G13],
  ] },
  'backlog-hygiene': { for: ['S6.2.4'], criteria: [
    ['no-orphans', 'No orphans', 2, false, G13 + ' / §10.2'],
    ['no-fake', 'No fake stories', 2, false, G13],
    ['no-duplicates', 'No duplicates', 1, false, G13],
  ] },
  'traceability': { for: ['S6.2.1', 'S6.2.2', 'S6.2.5'], includes: ['ubiquitous-language', 'backlog-hygiene'], criteria: [
    ['chain', 'Required chain complete for every story', 2, true, G13],
    ['matrix', 'Matrix complete', 1, false, G13],
  ], gateQuestion: 'Konsistent, rueckverfolgbar & DoR erfuellt?' },
  'run-report': { for: ['S7'], criteria: [
    ['evidence-mix', 'Evidence mix', 1, false, G13],
    ['risk-flags', 'Risk flags and forced loop exits', 1, false, G13],
    ['top5', 'Top-5 risk assumptions', 1, false, G13],
    ['cost', 'Cost', 1, false, G13],
  ] },
  // composite phase rubrics (inner gates K)
  'phase-1-1': { includes: ['research-markt-wettbewerb', 'idea-brief', 'vision-statement', 'lean-canvas', 'panel-grounding', 'vpc', 'assumptions-map'], criteria: [], gateQuestion: 'Geschaeftsmodell tragfaehig & UVP klar?' },
  'phase-1-2': { includes: ['impact-map', 'scoring', 'roadmap'], criteria: [], gateQuestion: 'Pfad zum Ziel plausibel?' },
  'phase-2-1': { includes: ['research-zielgruppe-voc', 'panel-grounding', 'interview-guide', 'transcript', 'persona', 'jtbd'], criteria: [], gateQuestion: 'Rollen & Jobs durch Quellen & Transkripte belegt?' },
  'phase-2-2': { includes: ['pov-hmw', 'ost', 'scoring'], criteria: [], gateQuestion: 'Problem loesungsneutral & fokussiert?' },
  'phase-3-1': { includes: ['research-domaene-prozesse-regulatorik', 'journey', 'service-blueprint'], criteria: [], gateQuestion: 'Future State ohne untragbare Backstage-Komplexitaet?' },
  'phase-4-1': { includes: ['story-map'], criteria: [], gateQuestion: 'Narrativ vollstaendig & kohaerent?' },
  'phase-4-2': { includes: ['walking-skeleton', 'mvp', 'scoring', 'roadmap'], criteria: [], gateQuestion: 'MVP schlank genug fuer Budget/Timebox?' },
  // phase-gate rubrics (PG)
  'gate-vision': { includes: ['phase-1-1', 'phase-1-2'], criteria: [
    ['coherent', 'Vision, business model and impact map tell one coherent story', 2, false, '§9.2'],
    ['no-refuted-kill', 'No kill assumption actively refuted by 🔗 evidence', 2, true, '§9.3'],
  ], gateQuestion: 'Vision & Geschaeftsziele tragfaehig?', panel: 'Proto panel vote: ≥2 of 3 personas ≥3/5.' },
  'gate-validierung': { includes: ['phase-2-1', 'phase-2-2', 'phase-3-1'], criteria: [
    ['problem-validated', 'Problem validated by transcripts and sources', 2, false, '§9.2'],
    ['cited-share', 'Evidence mix of personas/jtbd ≥50% 🔗', 1, false, '§9.3'],
    ['objections', 'Every Contrarian/Verweigerer objection addressed (answer or risk flag)', 1, false, '§9.2'],
    ['viability', 'Business model/solution viable (else pivot, max 2)', 2, false, '§9.3'],
  ], gateQuestion: 'Problem & Nutzerreise validiert?', panel: 'Full panel: ≥3 of 4 target personas desirability ≥4/5; Contrarian/Verweigerer votes do not count.' },
  'gate-mvp': { includes: ['phase-4-1', 'phase-4-2'], criteria: [
    ['feasible', 'MVP feasible for the target architecture and within budget/timebox', 2, true, '§9.2'],
    ['valuable', 'MVP delivers the core outcome for the target personas', 2, false, '§9.2'],
  ], gateQuestion: 'MVP tragfaehig & machbar?', panel: 'Full panel: ≥3 of 4 target personas "würde nutzen" ≥4/5 and ≥2 of 4 willing to pay at the lean-canvas price.' },
};
